import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'
import { DateTime } from 'luxon'

const inter = Inter({ subsets: ['latin'] })

export default function Home({dt}) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <h1>Get Static Props.</h1>
        <div>dt: {JSON.stringify(dt)}</div>
      </div>
    </>
  )
}

/*
export async function _getServerSideProps(context) {
  console.log("In getServerSideProps")
  const dt = DateTime.now();
  console.log(dt.toISO())
  return {
    props: {dt : dt.toISO()}, // will be passed to the page component as props
  }
}
*/

export async function getStaticProps(context) {
  console.log("In getStaticProps")
  const dt = DateTime.now();
  console.log(dt.toISO())
  return {
    revalidate: 5,
    props: {dt : dt.toISO()}, // will be passed to the page component as props
  }
}

